language: generic 
sudo: required
services:
  - docker

before-install:
  - docker build -t sakmalh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sakmalh/react-test npm test

after-success: 
  - docker build -t sakmalh/multi-nginx ./nginx
  - docker build -t sakmalh/multi-client ./client
  - docker build -t sakmalh/multi-worker ./worker
  - docker build -t sakmalh/multi-server ./server
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker login
  - docker push sakmalh/multi-nginx
  - docker push sakmalh/multi-client
  - docker push sakmalh/multi-worker
  - docker push sakmalh/multi-server