language: generic 
sudo: required
services:
  - docker

before-install:
  - docker build -t sakmalh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sakmalh/react-test npm test

after-success: 
  - docker build -t shakmalh/multi-nginx ./nginx
  - docker build -t shakmalh/multi-client ./client
  - docker build -t shakmalh/multi-worker ./worker
  - docker build -t shakmalh/multi-server ./server
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push shakmalh/multi-nginx
  - docker push shakmalh/multi-client
  - docker push shakmalh/multi-worker
  - docker push shakmalh/multi-server

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-041718486392"
  bucket_path: "docker-multi"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true